# Generated by Django 4.0.1 on 2022-03-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('konu', models.TextField()),
                ('resim', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('kategori', models.CharField(choices=[('Saglik', 'Sağlık'), ('Egitim', 'Eğitim'), ('Spor', 'Spor')], max_length=10)),
                ('tarih', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
